# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import math
from random import randrange, randint
my_dict1 = {}
my_dict2 = {}
my_dict3 = {}
counter = 1

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(705, 588)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 460, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(90, 50, 521, 21))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(24)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 0, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        #The subjects entered
        self.subject1 = QtWidgets.QLineEdit(self.centralwidget)
        self.subject1.setGeometry(QtCore.QRect(100, 160, 113, 20))
        self.subject1.setObjectName("subject1")
        self.subject2 = QtWidgets.QLineEdit(self.centralwidget)
        self.subject2.setGeometry(QtCore.QRect(100, 190, 113, 20))
        self.subject2.setObjectName("subject2")
        self.subject3 = QtWidgets.QLineEdit(self.centralwidget)
        self.subject3.setGeometry(QtCore.QRect(100, 220, 113, 20))
        self.subject3.setObjectName("subject3")
        self.subject4 = QtWidgets.QLineEdit(self.centralwidget)
        self.subject4.setGeometry(QtCore.QRect(100, 250, 113, 20))
        self.subject4.setObjectName("subject4")
        self.subject5 = QtWidgets.QLineEdit(self.centralwidget)
        self.subject5.setGeometry(QtCore.QRect(100, 280, 113, 20))
        self.subject5.setObjectName("subject5")
        self.subject6 = QtWidgets.QLineEdit(self.centralwidget)
        self.subject6.setGeometry(QtCore.QRect(100, 310, 113, 20))
        self.subject6.setObjectName("subject6") 
        self.subject7 = QtWidgets.QLineEdit(self.centralwidget)
        self.subject7.setGeometry(QtCore.QRect(100, 340, 113, 20))
        self.subject7.setObjectName("subject7")       
        self.subject8 = QtWidgets.QLineEdit(self.centralwidget)
        self.subject8.setGeometry(QtCore.QRect(100, 370, 113, 20))
        self.subject8.setObjectName("subject8")
        self.subject9 = QtWidgets.QLineEdit(self.centralwidget)
        self.subject9.setGeometry(QtCore.QRect(100, 400, 113, 20))
        self.subject9.setObjectName("subject9")
        self.subject10 = QtWidgets.QLineEdit(self.centralwidget)
        self.subject10.setGeometry(QtCore.QRect(100, 430, 113, 20))
        self.subject10.setObjectName("subject10")
        
        #The expected number of students
        self.number1 = QtWidgets.QLineEdit(self.centralwidget)
        self.number1.setGeometry(QtCore.QRect(290, 160, 111, 20))
        self.number1.setObjectName("number1")
        self.number2 = QtWidgets.QLineEdit(self.centralwidget)
        self.number2.setGeometry(QtCore.QRect(290, 190, 113, 20))
        self.number2.setObjectName("number2")
        self.number3 = QtWidgets.QLineEdit(self.centralwidget)
        self.number3.setGeometry(QtCore.QRect(290, 220, 113, 20))
        self.number3.setObjectName("number3")
        self.number4 = QtWidgets.QLineEdit(self.centralwidget)
        self.number4.setGeometry(QtCore.QRect(290, 250, 113, 20))
        self.number4.setObjectName("number4")
        self.number5 = QtWidgets.QLineEdit(self.centralwidget)
        self.number5.setGeometry(QtCore.QRect(290, 280, 113, 20))
        self.number5.setObjectName("number5")
        self.number6 = QtWidgets.QLineEdit(self.centralwidget)
        self.number6.setGeometry(QtCore.QRect(290, 310, 113, 20))
        self.number6.setObjectName("number6")
        self.number7 = QtWidgets.QLineEdit(self.centralwidget)
        self.number7.setGeometry(QtCore.QRect(290, 340, 113, 20))
        self.number7.setObjectName("number7")
        self.number8 = QtWidgets.QLineEdit(self.centralwidget)
        self.number8.setGeometry(QtCore.QRect(290, 370, 113, 20))
        self.number8.setObjectName("number8")
        self.number9 = QtWidgets.QLineEdit(self.centralwidget)
        self.number9.setGeometry(QtCore.QRect(290, 400, 113, 20))
        self.number9.setObjectName("number9")
        self.number10 = QtWidgets.QLineEdit(self.centralwidget)
        self.number10.setGeometry(QtCore.QRect(290, 430, 113, 20))
        self.number10.setObjectName("number10")

        #The alloted credit hours
        self.hours1 = QtWidgets.QLineEdit(self.centralwidget)
        self.hours1.setGeometry(QtCore.QRect(480, 160, 111, 20))
        self.hours1.setObjectName("hours1")
        self.hours2 = QtWidgets.QLineEdit(self.centralwidget)
        self.hours2.setGeometry(QtCore.QRect(480, 190, 113, 20))
        self.hours2.setObjectName("hours2")
        self.hours3 = QtWidgets.QLineEdit(self.centralwidget)
        self.hours3.setGeometry(QtCore.QRect(480, 220, 113, 20))
        self.hours3.setObjectName("hours3")
        self.hours4 = QtWidgets.QLineEdit(self.centralwidget)
        self.hours4.setGeometry(QtCore.QRect(480, 250, 113, 20))
        self.hours4.setObjectName("hours4")
        self.hours5 = QtWidgets.QLineEdit(self.centralwidget)
        self.hours5.setGeometry(QtCore.QRect(480, 280, 113, 20))
        self.hours5.setObjectName("hours5")
        self.hours6 = QtWidgets.QLineEdit(self.centralwidget)
        self.hours6.setGeometry(QtCore.QRect(480, 310, 113, 20))
        self.hours6.setObjectName("hours6")
        self.hours7 = QtWidgets.QLineEdit(self.centralwidget)
        self.hours7.setGeometry(QtCore.QRect(480, 340, 113, 20))
        self.hours7.setObjectName("hours7")
        self.hours8 = QtWidgets.QLineEdit(self.centralwidget)
        self.hours8.setGeometry(QtCore.QRect(480, 370, 113, 20))
        self.hours8.setObjectName("hours8")
        self.hours9 = QtWidgets.QLineEdit(self.centralwidget)
        self.hours9.setGeometry(QtCore.QRect(480, 400, 113, 20))
        self.hours9.setObjectName("hours9")
        self.hours10 = QtWidgets.QLineEdit(self.centralwidget)
        self.hours10.setGeometry(QtCore.QRect(480, 430, 113, 20))
        self.hours10.setObjectName("hours10")
        
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 130, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 130, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(490, 130, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setEnabled(True)
        self.label_5.setGeometry(QtCore.QRect(290, 90, 111, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 232, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 232, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 232, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.label_5.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_5.setAcceptDrops(False)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAutoFillBackground(True)
        self.label_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 460, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 705, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # To add subjects from all forms into a dictionary
        self.pushButton_2.clicked.connect(self.add_subject)

        # To produce a new blank form for each class of data
        self.pushButton_2.clicked.connect(self.next_class)

        # To generate results
        self.pushButton.clicked.connect(self.generate_button)
        
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Generate"))
        self.label.setText(_translate("MainWindow", "Generator X"))
        self.label_2.setText(_translate("MainWindow", "Course Name"))
        self.label_3.setText(_translate("MainWindow", "Number of Students"))
        self.label_4.setText(_translate("MainWindow", "Credit Hours"))
        self.label_5.setText(_translate("MainWindow", "dept_level"))
        self.pushButton_2.setText(_translate("MainWindow", "Next Class"))

    # The Next Class Button
    def next_class(self):
        ui.setupUi(MainWindow)
        MainWindow.show()

    # The generate button
    def generate_button(self):
        input_text=""
        input_text = self.subject1.text()
        print (input_text)
     
    # To store subject inputs
    def add_subject(self): 
         global counter
         key = counter
         
         global my_dict1, my_dict2, my_dict3
         
         my_dict1[key] = self.subject1.text()
         my_dict2[key] = self.number1.text()
         my_dict3[key] = self.hours1.text()
         
         counter += 1
         key = counter
         my_dict1[key] = self.subject2.text()
         my_dict2[key] = self.number2.text()
         my_dict3[key] = self.hours2.text()
         
         counter += 1
         key = counter
         my_dict1[key] = self.subject3.text()
         my_dict2[key] = self.number3.text()
         my_dict3[key] = self.hours3.text()
         
         counter += 1
         key = counter
         my_dict1[key] = self.subject4.text()
         my_dict2[key] = self.number4.text()
         my_dict3[key] = self.hours4.text()
         
         counter += 1
         key = counter
         my_dict1[key] = self.subject5.text()
         my_dict2[key] = self.number5.text()
         my_dict3[key] = self.hours5.text()
         
         counter += 1
         key = counter
         my_dict1[key] = self.subject6.text()
         my_dict2[key] = self.number6.text()
         my_dict3[key] = self.hours6.text()
         
         counter += 1
         key = counter
         my_dict1[key] = self.subject7.text()
         my_dict2[key] = self.number7.text()
         my_dict3[key] = self.hours7.text()
         
         counter += 1
         key = counter
         my_dict1[key] = self.subject8.text()
         my_dict2[key] = self.number8.text()
         my_dict3[key] = self.hours8.text()
         
         counter += 1
         key = counter
         my_dict1[key] = self.subject9.text()
         my_dict2[key] = self.number9.text()
         my_dict3[key] = self.hours9.text()
         
         counter += 1
         key = counter
         my_dict1[key] = self.subject10.text()
         my_dict2[key] = self.number10.text()
         my_dict3[key] = self.hours10.text()
         counter += 1
         
        

#Class for the courses offered
class subjects:
    count = []

    def __init__(self, name, number_of_students, hours):
        self.name = name
        self.number_of_students = int(number_of_students)
        self.hours = int(hours)
        subjects.count.append(self)
    
    def __del__(self):
        subjects.count.remove(self)
    
    @staticmethod
    def bit():
        a = len(subjects.count)
        global bitstring, bitstring2
        bitstring= ''
        bitstring2 = ''
        for i in range (math.ceil(math.log(a, 2))):
            bitstring += str(randrange(0,2))
            bitstring2 += str(randrange(0,2))
        return bitstring, bitstring2


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


